export const GET_DATA_LOADING = "GET_DATA_LOADING"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_ERROR = "GET_DATA_ERROR"
export const GET_PRODUCTS_DATA ="GET_PRODUCTS_DATA" ;
export const SORT_PRODUCTS = "SORT_PRODUCTS"
export const FILTER_PRODUCTS = "FILTER_PRODUCTS"

